version: '2'

services:

  db:
    #restart: always
    image: postgres:10.5
    container_name: tt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd@1
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - TZ=Asia/Manila
    volumes:
      - ./docker/db/dbini:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5438:5432" # Only for tests
    networks:
      - tt

  app:
    build: app
    networks:
      - tt
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI:   "postgresql://postgres:passw0rd@1@tt-db:5432/postgres"

networks:
  tt:
